### ISSUE TITLE
BitbucketResourceOwner::getEmail

### ISSUE THREAD

**Issue by antonmedv** [stevenmaguire/oauth2-bitbucket#6]
Please add `BitbucketResourceOwner::getEmail`.

**Comment by stevenmaguire** [comment]
Unless I am missing something, email is not currently available via the Bitbucket API.

https://confluence.atlassian.com/bitbucket/user-endpoint-296092264.html#userEndpoint-GETauserprofile

Without API access to this information there is no way to implement this.

**Comment by antonmedv** [comment]
What about Oauth v2?

**Comment by stevenmaguire** [comment]
This package is for Bitbucket's support of OAuth2. The authorization protocol has nothing to do with the data that the providers expose via their API. Bitbucket does not appear to provide a means to obtain a user's email address.

**Comment by therockers** [comment]
You actually can get the user's email from Bitbucket now. Assuming you already have the access token generated, all you really need to do is another `$_GET` request to the `/emails` URL along the access token and the access bearer and you can actually get the email back. Something like so

```
$curl = curl_init();

curl_setopt_array($curl, [
	CURLOPT_RETURNTRANSFER => 1,
	CURLOPT_URL => 'https://bitbucket.org/api/1.0/users/' . $user->getUsername() . '/emails?access_token=' . $token->getToken(),
	CURLOPT_HTTPHEADER, [
		'Authorization' => 'Bearer ' . $token->getToken()
	]
]);

$result = curl_exec($curl);

curl_close($curl);

$decode = json_decode($result);

print_r($decode);
```

Assuming you're also using the code snippet from the example code in the `README.md` file. The end result would be an array that looks something like this.

```
Array
(
    [0] => stdClass Object
        (
            [active] => 1
            [is_atlassian_id] => 1
            [email] => email@address.com
            [primary] => 1
        )

)
```

email@address.com is a dummy to demonstrate what the cURL request sends back.
