### ISSUE TITLE
Is it possible to use this with rest api ? 

### ISSUE THREAD

**Issue by razamoh** [stevenmaguire/oauth2-bitbucket#8]

**Comment by stevenmaguire** [comment]
@razamoh Technically, yes, you can use it with the BitBucket API. There is a method available in this client that allows you to create an authorized request with a given access token. You can review the code here: https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L557

My strongest recommendation would be to find a dedicated BitBucket API client package to use for regularly API requests and only use this package for obtaining access tokens on behalf of your users. I feel that your developer experience will be far better with a dedicated API client package when compared to using the built-in `getAuthenticatedRequest` method. 

Good luck!
